version: '3.7'
services:
  postgres:
    image: postgres:12.1
    ports:
      - 5432:5432
  web:
    image: strapi/strapi
    container_name: unikorns-csm
    restart: unless-stopped
    env_file: .env
    links:
      - postgres
    volumes:
      - ./app:/unikorns-csm
    ports:
      - "1337:1337"
